- menu_name: "Servicios"

- name: "Contacto"
  url: "/contact/"
  title: "Contact"

- name: "RSS"
  url: "/feed.xml"
  title: "Suscríbete al feed RSS"

- name: "Atom"
  url: "/atom.xml"
  title: "Subscríbete al feed Atom"

- name: "Traducción"
  url: "https://www.transifex.com/linuxdeepin/"
  title: "Equipo de traducción para aplicaciones Deepin"
